import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "../theme";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import ClientProvider from "./clientProvider";
import Navbar from "./components/navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body className={inter.className}>
            <Suspense fallback={<div>Loading...</div>}>
              <ClientProvider>
                <Navbar />
                {children}
              </ClientProvider>
            </Suspense>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
